version: '2.4'

services:
  backup:
    container_name: backup
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./dropbear:/etc/dropbear
      - ./backup:/home/rbackup
    environment:
      - BACKUP_USER=rbackup
    ports:
      - 2222:22/tcp
